// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKkLbJVBLGV5R1LVz8_lbhHEAbg24vTow',
    appId: '1:730039735191:web:4897bca62fea855e6daad2',
    messagingSenderId: '730039735191',
    projectId: 'recout-68e18',
    authDomain: 'recout-68e18.firebaseapp.com',
    storageBucket: 'recout-68e18.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVlQWVR22OGooDUPlI_LvRfDV20DS7u2Y',
    appId: '1:730039735191:android:6fdbdb616e121df76daad2',
    messagingSenderId: '730039735191',
    projectId: 'recout-68e18',
    storageBucket: 'recout-68e18.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7DQNPcniyKJ2azXwVm99XwI-O2ZlYhNk',
    appId: '1:730039735191:ios:ae426bca8fa367786daad2',
    messagingSenderId: '730039735191',
    projectId: 'recout-68e18',
    storageBucket: 'recout-68e18.firebasestorage.app',
    iosBundleId: 'com.example.recout',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7DQNPcniyKJ2azXwVm99XwI-O2ZlYhNk',
    appId: '1:730039735191:ios:ae426bca8fa367786daad2',
    messagingSenderId: '730039735191',
    projectId: 'recout-68e18',
    storageBucket: 'recout-68e18.firebasestorage.app',
    iosBundleId: 'com.example.recout',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKkLbJVBLGV5R1LVz8_lbhHEAbg24vTow',
    appId: '1:730039735191:web:cab44c8b2be79eb86daad2',
    messagingSenderId: '730039735191',
    projectId: 'recout-68e18',
    authDomain: 'recout-68e18.firebaseapp.com',
    storageBucket: 'recout-68e18.firebasestorage.app',
  );
}
