// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcx-HhpTW7xxfZTWrSiI7Z3lMD7iGuzVg',
    appId: '1:860290219507:web:11715aa24671902589a686',
    messagingSenderId: '860290219507',
    projectId: 'recout-13b03',
    authDomain: 'recout-13b03.firebaseapp.com',
    storageBucket: 'recout-13b03.firebasestorage.app',
    measurementId: 'G-1RD6TZGHTW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdqiC-Dtv1xnnxerEFsOOW5flm8uXitAk',
    appId: '1:860290219507:android:3ba23db073a2a0bc89a686',
    messagingSenderId: '860290219507',
    projectId: 'recout-13b03',
    storageBucket: 'recout-13b03.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBC4ZjxFQmJVjQIbexmhvBoxQDWjRWSKHo',
    appId: '1:860290219507:ios:816de9438f6a2c9289a686',
    messagingSenderId: '860290219507',
    projectId: 'recout-13b03',
    storageBucket: 'recout-13b03.firebasestorage.app',
    iosBundleId: 'hu.toliver.recout',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBC4ZjxFQmJVjQIbexmhvBoxQDWjRWSKHo',
    appId: '1:860290219507:ios:816de9438f6a2c9289a686',
    messagingSenderId: '860290219507',
    projectId: 'recout-13b03',
    storageBucket: 'recout-13b03.firebasestorage.app',
    iosBundleId: 'hu.toliver.recout',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcx-HhpTW7xxfZTWrSiI7Z3lMD7iGuzVg',
    appId: '1:860290219507:web:8cafe3905a1b0b2e89a686',
    messagingSenderId: '860290219507',
    projectId: 'recout-13b03',
    authDomain: 'recout-13b03.firebaseapp.com',
    storageBucket: 'recout-13b03.firebasestorage.app',
    measurementId: 'G-SNVGGNCNXM',
  );

}