
#name: Deploy to Firebase Hosting
#on:
#  pull_request:
#    branches:
#      - release
#  push:
#    branches:
#      - release
#
#permissions:
#  checks: write
#  contents: read
#  pull-requests: write
#
#jobs:
#  deploy:
#    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checking out
#        uses: actions/checkout@v3
#      - uses: subosito/flutter-action@v1
#        with:
#          channel: 'stable'
#          flutter-version: 3.32.0
#      - name: Flutter get pub!
#        run: flutter pub get
#      - name: Flutter enable web!
#        run: flutter config --enable-web
#      - name: Flutter build web!
#        run: flutter build web
#      - name: Archive Production Artifact
#        uses: actions/upload-artifact@v4
#        with:
#          name: web-build
#          path: build/web
#      - name: Deploy to Firebase
#        uses: FirebaseExtended/action-hosting-deploy@v0
#        with:
#          channelId: ${{ github.event_name == 'pull_request' && 'preview' || 'live' }}
#          repoToken: ${{ secrets.GITHUB_TOKEN }}
#          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_RECOUT_13B03 }}
#          projectId: recout-13b03
#          expires: 2d
